name: Rust CI (Windows)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: test ${{ matrix.rust }}
    runs-on: windows-latest
    timeout-minutes: 12
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.rust }}
      - name: Build default features
        run: cargo build
      - name: Build with hotpath feature
        run: cargo build --features hotpath
      - name: Build with hotpath-alloc feature
        run: cargo build --features='hotpath,hotpath-alloc'
      - name: Run lib tests
        run: |
          cargo test --lib --features hotpath
      - name: Run CLI tests
        run: |
          cargo test -p hotpath --bin hotpath --features=tui
      - name: Run functions tests
        run: |
          cargo test --features hotpath --test functions -- --nocapture --test-threads=1
      - name: Run streams tests
        run: |
          cargo test --features hotpath --test streams -- --nocapture --test-threads=1
      - name: Run channels crossbeam tests
        run: |
          cargo test --features hotpath --test channels_crossbeam -- --nocapture --test-threads=1
      - name: Run channels futures tests
        run: |
          cargo test --features hotpath --test channels_ftc -- --nocapture --test-threads=1
      - name: Run channels std tests
        run: |
          cargo test --features hotpath --test channels_std -- --nocapture --test-threads=1
