name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: test ${{ matrix.rust }}
    runs-on: ubuntu-latest
    timeout-minutes: 12
    strategy:
      fail-fast: false
      matrix:
        rust:
          - 1.89
          - stable
          - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.rust }}
      - uses: taiki-e/install-action@cargo-audit
        if: matrix.rust == 'stable'
      - name: Check no features
        run: |
          cargo check
      - name: Check all features
        run: |
          cargo check --all-features
      - name: Check hotpath feature (time mode)
        run: |
          cargo check --features hotpath
      - name: Check hotpath-alloc
        run: |
          cargo check --features "hotpath,hotpath-alloc"
      - name: Fmt
        if: matrix.rust == 'stable'
        run: |
          cargo fmt --all --check
      - name: Lint (default features)
        if: matrix.rust == 'stable'
        run: |
          cargo clippy --all --features hotpath -- -D warnings
      - name: Lint (--all-features)
        if: matrix.rust == 'stable'
        run: |
          cargo clippy --all --all-features -- -D warnings
      - name: Lint (hotpath-alloc)
        if: matrix.rust == 'stable'
        run: |
          cargo clippy --all --features "hotpath,hotpath-alloc" -- -D warnings
      - name: Audit
        if: matrix.rust == 'stable'
        run: |
          cargo audit --ignore RUSTSEC-2023-0071
      - name: Run lib tests
        run: |
          cargo test --lib --features hotpath
      - name: Check TUI build
        run: |
          cargo check -p hotpath --bin hotpath --features=tui
      - name: Check CI build
        run: |
          cargo check -p hotpath --bin hotpath-ci --features=ci
      - name: Run CLI tests
        run: |
          cargo test -p hotpath --bin hotpath --features=tui
      - name: Run functions tests
        run: |
          cargo test --features hotpath --test functions -- --nocapture --test-threads=1
      - name: Run streams tests
        run: |
          cargo test --features hotpath --test streams -- --nocapture --test-threads=1
      - name: Run channels crossbeam tests
        run: |
          cargo test --features hotpath --test channels_crossbeam -- --nocapture --test-threads=1
      - name: Run channels futures tests
        run: |
          cargo test --features hotpath --test channels_ftc -- --nocapture --test-threads=1
      - name: Run channels std tests
        run: |
          cargo test --features hotpath --test channels_std -- --nocapture --test-threads=1
      - name: Run channels tokio tests
        run: |
          cargo test --features hotpath --test channels_tokio -- --nocapture --test-threads=1
      - name: Run threads tests
        run: |
          cargo test --features hotpath --test threads -- --nocapture --test-threads=1
      - name: Run futures tests
        run: |
          cargo test --features hotpath --test futures -- --nocapture --test-threads=1
